// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: file_importer.proto
#ifndef GRPC_file_5fimporter_2eproto__INCLUDED
#define GRPC_file_5fimporter_2eproto__INCLUDED

#include "file_importer.pb.h"

#include <functional>
#include <grpcpp/generic/async_generic_service.h>
#include <grpcpp/support/async_stream.h>
#include <grpcpp/support/async_unary_call.h>
#include <grpcpp/support/client_callback.h>
#include <grpcpp/client_context.h>
#include <grpcpp/completion_queue.h>
#include <grpcpp/support/message_allocator.h>
#include <grpcpp/support/method_handler.h>
#include <grpcpp/impl/codegen/proto_utils.h>
#include <grpcpp/impl/rpc_method.h>
#include <grpcpp/support/server_callback.h>
#include <grpcpp/impl/codegen/server_callback_handlers.h>
#include <grpcpp/server_context.h>
#include <grpcpp/impl/service_type.h>
#include <grpcpp/impl/codegen/status.h>
#include <grpcpp/support/stub_options.h>
#include <grpcpp/support/sync_stream.h>

namespace file_importer {

// service definition.
class FileImporter final {
 public:
  static constexpr char const* service_full_name() {
    return "file_importer.FileImporter";
  }
  class StubInterface {
   public:
    virtual ~StubInterface() {}
    virtual ::grpc::Status Import3dFile(::grpc::ClientContext* context, const ::file_importer::ImportFileRequest& request, ::file_importer::ImportFileResponse* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::file_importer::ImportFileResponse>> AsyncImport3dFile(::grpc::ClientContext* context, const ::file_importer::ImportFileRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::file_importer::ImportFileResponse>>(AsyncImport3dFileRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::file_importer::ImportFileResponse>> PrepareAsyncImport3dFile(::grpc::ClientContext* context, const ::file_importer::ImportFileRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::file_importer::ImportFileResponse>>(PrepareAsyncImport3dFileRaw(context, request, cq));
    }
    class async_interface {
     public:
      virtual ~async_interface() {}
      virtual void Import3dFile(::grpc::ClientContext* context, const ::file_importer::ImportFileRequest* request, ::file_importer::ImportFileResponse* response, std::function<void(::grpc::Status)>) = 0;
      virtual void Import3dFile(::grpc::ClientContext* context, const ::file_importer::ImportFileRequest* request, ::file_importer::ImportFileResponse* response, ::grpc::ClientUnaryReactor* reactor) = 0;
    };
    typedef class async_interface experimental_async_interface;
    virtual class async_interface* async() { return nullptr; }
    class async_interface* experimental_async() { return async(); }
   private:
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::file_importer::ImportFileResponse>* AsyncImport3dFileRaw(::grpc::ClientContext* context, const ::file_importer::ImportFileRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::file_importer::ImportFileResponse>* PrepareAsyncImport3dFileRaw(::grpc::ClientContext* context, const ::file_importer::ImportFileRequest& request, ::grpc::CompletionQueue* cq) = 0;
  };
  class Stub final : public StubInterface {
   public:
    Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());
    ::grpc::Status Import3dFile(::grpc::ClientContext* context, const ::file_importer::ImportFileRequest& request, ::file_importer::ImportFileResponse* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::file_importer::ImportFileResponse>> AsyncImport3dFile(::grpc::ClientContext* context, const ::file_importer::ImportFileRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::file_importer::ImportFileResponse>>(AsyncImport3dFileRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::file_importer::ImportFileResponse>> PrepareAsyncImport3dFile(::grpc::ClientContext* context, const ::file_importer::ImportFileRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::file_importer::ImportFileResponse>>(PrepareAsyncImport3dFileRaw(context, request, cq));
    }
    class async final :
      public StubInterface::async_interface {
     public:
      void Import3dFile(::grpc::ClientContext* context, const ::file_importer::ImportFileRequest* request, ::file_importer::ImportFileResponse* response, std::function<void(::grpc::Status)>) override;
      void Import3dFile(::grpc::ClientContext* context, const ::file_importer::ImportFileRequest* request, ::file_importer::ImportFileResponse* response, ::grpc::ClientUnaryReactor* reactor) override;
     private:
      friend class Stub;
      explicit async(Stub* stub): stub_(stub) { }
      Stub* stub() { return stub_; }
      Stub* stub_;
    };
    class async* async() override { return &async_stub_; }

   private:
    std::shared_ptr< ::grpc::ChannelInterface> channel_;
    class async async_stub_{this};
    ::grpc::ClientAsyncResponseReader< ::file_importer::ImportFileResponse>* AsyncImport3dFileRaw(::grpc::ClientContext* context, const ::file_importer::ImportFileRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::file_importer::ImportFileResponse>* PrepareAsyncImport3dFileRaw(::grpc::ClientContext* context, const ::file_importer::ImportFileRequest& request, ::grpc::CompletionQueue* cq) override;
    const ::grpc::internal::RpcMethod rpcmethod_Import3dFile_;
  };
  static std::unique_ptr<Stub> NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());

  class Service : public ::grpc::Service {
   public:
    Service();
    virtual ~Service();
    virtual ::grpc::Status Import3dFile(::grpc::ServerContext* context, const ::file_importer::ImportFileRequest* request, ::file_importer::ImportFileResponse* response);
  };
  template <class BaseClass>
  class WithAsyncMethod_Import3dFile : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_Import3dFile() {
      ::grpc::Service::MarkMethodAsync(0);
    }
    ~WithAsyncMethod_Import3dFile() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status Import3dFile(::grpc::ServerContext* /*context*/, const ::file_importer::ImportFileRequest* /*request*/, ::file_importer::ImportFileResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestImport3dFile(::grpc::ServerContext* context, ::file_importer::ImportFileRequest* request, ::grpc::ServerAsyncResponseWriter< ::file_importer::ImportFileResponse>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  typedef WithAsyncMethod_Import3dFile<Service > AsyncService;
  template <class BaseClass>
  class WithCallbackMethod_Import3dFile : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithCallbackMethod_Import3dFile() {
      ::grpc::Service::MarkMethodCallback(0,
          new ::grpc::internal::CallbackUnaryHandler< ::file_importer::ImportFileRequest, ::file_importer::ImportFileResponse>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::file_importer::ImportFileRequest* request, ::file_importer::ImportFileResponse* response) { return this->Import3dFile(context, request, response); }));}
    void SetMessageAllocatorFor_Import3dFile(
        ::grpc::MessageAllocator< ::file_importer::ImportFileRequest, ::file_importer::ImportFileResponse>* allocator) {
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::GetHandler(0);
      static_cast<::grpc::internal::CallbackUnaryHandler< ::file_importer::ImportFileRequest, ::file_importer::ImportFileResponse>*>(handler)
              ->SetMessageAllocator(allocator);
    }
    ~WithCallbackMethod_Import3dFile() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status Import3dFile(::grpc::ServerContext* /*context*/, const ::file_importer::ImportFileRequest* /*request*/, ::file_importer::ImportFileResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* Import3dFile(
      ::grpc::CallbackServerContext* /*context*/, const ::file_importer::ImportFileRequest* /*request*/, ::file_importer::ImportFileResponse* /*response*/)  { return nullptr; }
  };
  typedef WithCallbackMethod_Import3dFile<Service > CallbackService;
  typedef CallbackService ExperimentalCallbackService;
  template <class BaseClass>
  class WithGenericMethod_Import3dFile : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_Import3dFile() {
      ::grpc::Service::MarkMethodGeneric(0);
    }
    ~WithGenericMethod_Import3dFile() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status Import3dFile(::grpc::ServerContext* /*context*/, const ::file_importer::ImportFileRequest* /*request*/, ::file_importer::ImportFileResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithRawMethod_Import3dFile : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_Import3dFile() {
      ::grpc::Service::MarkMethodRaw(0);
    }
    ~WithRawMethod_Import3dFile() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status Import3dFile(::grpc::ServerContext* /*context*/, const ::file_importer::ImportFileRequest* /*request*/, ::file_importer::ImportFileResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestImport3dFile(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawCallbackMethod_Import3dFile : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawCallbackMethod_Import3dFile() {
      ::grpc::Service::MarkMethodRawCallback(0,
          new ::grpc::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response) { return this->Import3dFile(context, request, response); }));
    }
    ~WithRawCallbackMethod_Import3dFile() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status Import3dFile(::grpc::ServerContext* /*context*/, const ::file_importer::ImportFileRequest* /*request*/, ::file_importer::ImportFileResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* Import3dFile(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_Import3dFile : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithStreamedUnaryMethod_Import3dFile() {
      ::grpc::Service::MarkMethodStreamed(0,
        new ::grpc::internal::StreamedUnaryHandler<
          ::file_importer::ImportFileRequest, ::file_importer::ImportFileResponse>(
            [this](::grpc::ServerContext* context,
                   ::grpc::ServerUnaryStreamer<
                     ::file_importer::ImportFileRequest, ::file_importer::ImportFileResponse>* streamer) {
                       return this->StreamedImport3dFile(context,
                         streamer);
                  }));
    }
    ~WithStreamedUnaryMethod_Import3dFile() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status Import3dFile(::grpc::ServerContext* /*context*/, const ::file_importer::ImportFileRequest* /*request*/, ::file_importer::ImportFileResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedImport3dFile(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::file_importer::ImportFileRequest,::file_importer::ImportFileResponse>* server_unary_streamer) = 0;
  };
  typedef WithStreamedUnaryMethod_Import3dFile<Service > StreamedUnaryService;
  typedef Service SplitStreamedService;
  typedef WithStreamedUnaryMethod_Import3dFile<Service > StreamedService;
};

}  // namespace file_importer


#endif  // GRPC_file_5fimporter_2eproto__INCLUDED
