// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: file_importer.proto

#include "file_importer.pb.h"
#include "file_importer.grpc.pb.h"

#include <functional>
#include <grpcpp/support/async_stream.h>
#include <grpcpp/support/async_unary_call.h>
#include <grpcpp/impl/channel_interface.h>
#include <grpcpp/impl/client_unary_call.h>
#include <grpcpp/support/client_callback.h>
#include <grpcpp/support/message_allocator.h>
#include <grpcpp/support/method_handler.h>
#include <grpcpp/impl/rpc_service_method.h>
#include <grpcpp/support/server_callback.h>
#include <grpcpp/impl/codegen/server_callback_handlers.h>
#include <grpcpp/server_context.h>
#include <grpcpp/impl/service_type.h>
#include <grpcpp/support/sync_stream.h>
namespace file_importer {

static const char* FileImporter_method_names[] = {
  "/file_importer.FileImporter/Import3dFile",
};

std::unique_ptr< FileImporter::Stub> FileImporter::NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options) {
  (void)options;
  std::unique_ptr< FileImporter::Stub> stub(new FileImporter::Stub(channel, options));
  return stub;
}

FileImporter::Stub::Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options)
  : channel_(channel), rpcmethod_Import3dFile_(FileImporter_method_names[0], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  {}

::grpc::Status FileImporter::Stub::Import3dFile(::grpc::ClientContext* context, const ::file_importer::ImportFileRequest& request, ::file_importer::ImportFileResponse* response) {
  return ::grpc::internal::BlockingUnaryCall< ::file_importer::ImportFileRequest, ::file_importer::ImportFileResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_Import3dFile_, context, request, response);
}

void FileImporter::Stub::async::Import3dFile(::grpc::ClientContext* context, const ::file_importer::ImportFileRequest* request, ::file_importer::ImportFileResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::file_importer::ImportFileRequest, ::file_importer::ImportFileResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_Import3dFile_, context, request, response, std::move(f));
}

void FileImporter::Stub::async::Import3dFile(::grpc::ClientContext* context, const ::file_importer::ImportFileRequest* request, ::file_importer::ImportFileResponse* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_Import3dFile_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::file_importer::ImportFileResponse>* FileImporter::Stub::PrepareAsyncImport3dFileRaw(::grpc::ClientContext* context, const ::file_importer::ImportFileRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::file_importer::ImportFileResponse, ::file_importer::ImportFileRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_Import3dFile_, context, request);
}

::grpc::ClientAsyncResponseReader< ::file_importer::ImportFileResponse>* FileImporter::Stub::AsyncImport3dFileRaw(::grpc::ClientContext* context, const ::file_importer::ImportFileRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncImport3dFileRaw(context, request, cq);
  result->StartCall();
  return result;
}

FileImporter::Service::Service() {
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      FileImporter_method_names[0],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< FileImporter::Service, ::file_importer::ImportFileRequest, ::file_importer::ImportFileResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](FileImporter::Service* service,
             ::grpc::ServerContext* ctx,
             const ::file_importer::ImportFileRequest* req,
             ::file_importer::ImportFileResponse* resp) {
               return service->Import3dFile(ctx, req, resp);
             }, this)));
}

FileImporter::Service::~Service() {
}

::grpc::Status FileImporter::Service::Import3dFile(::grpc::ServerContext* context, const ::file_importer::ImportFileRequest* request, ::file_importer::ImportFileResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}


}  // namespace file_importer

